version: 1.0
provider:
  name: openfaas
  gateway: http://10.230.166.1:8080
functions:
  h-memory:
    lang: hybrid-py
    handler: ./h-memory
    image: jialianghuang/h-memory:latest
    limits:
      cpu: 1
    port: 5000
    environment:
      port: 9000

  h-hello-world:
    lang: hybrid-py
    handler: ./h-hello-world
    image: jialianghuang/h-hello-world:latest
    limits:
      memory: 128M
      cpu: 1
    port: 5001
    environment:
      port: 9001

  chameleon:
    lang: hybrid-py
    handler: ./chameleon
    image: jialianghuang/chameleon:latest
    limits:
      memory: 300M
      cpu: 1
    port: 5002
    environment:
      port: 9002

  dynamic-html:
    lang: hybrid-py
    handler: ./dynamic-html
    image: jialianghuang/dynamic-html:latest
    limits:
      memory: 64M
      cpu: 1
    port: 5003
    environment:
      port: 9003

  image-processing:
    lang: hybrid-py
    handler: ./image-processing
    image: jialianghuang/image-processing:latest
    limits:
      memory: 224M
      cpu: 1
    port: 5004
    environment:
      port: 9004

  pyaes:
    lang: hybrid-py
    handler: ./pyaes
    image: jialianghuang/pyaes:latest
    limits:
      memory: 64M
      cpu: 1
    port: 5005
    environment:
      port: 9005

  image-recognition:
    lang: hybrid-py
    handler: ./image-recognition
    image: jialianghuang/image-recognition:latest
    limits:
      memory: 768M
      cpu: 2
    port: 5006
    environment:
      port: 9006
      exec_timeout: 50
      write_timeout: 55

  video-processing:
    lang: hybrid-py
    handler: ./video-processing
    image: jialianghuang/video-processing:latest
    limits:
      memory: 224M
      cpu: 1
    port: 5007
    environment:
      port: 9007

  crypto:
    lang: hybrid-node18
    handler: ./crypto
    image: jialianghuang/crypto:latest
    limits:
      memory: 84M
      cpu: 1
    port: 5008
    environment:
      port: 9008

  image-flip-rotate:
    lang: hybrid-node18
    handler: ./image-flip-rotate
    image: jialianghuang/image-flip-rotate:latest
    limits:
      memory: 560M
      cpu: 1
    port: 5009
    environment:
      port: 9009


  js-json-serde:
    lang: hybrid-node18
    handler: ./js-json-serde
    image: jialianghuang/js-json-serde:latest
    limits:
      memory: 100M
      cpu: 1
    port: 5010
    environment:
      port: 9010

  json-serde:
    lang: hybrid-py
    handler: ./json-serde
    image: jialianghuang/json-serde:latest
    limits:
      memory: 100M
      cpu: 1
    port: 5011
    environment:
      port: 9011

  pagerank:
    lang: hybrid-py
    handler: ./pagerank
    image: jialianghuang/pagerank:latest
    limits:
      memory: 280M
      cpu: 1
    port: 5012
    environment:
      port: 9012


  chameleon_1:
    lang: hybrid-py
    handler: ./chameleon
    image: jialianghuang/chameleon:latest
    limits:
      memory: 300M
      cpu: 1
    port: 5102
    environment:
      port: 9102 

  dynamic-html_1:
    lang: hybrid-py
    handler: ./dynamic-html
    image: jialianghuang/dynamic-html:latest
    limits:
      memory: 128M
      cpu: 1
    port: 5103
    environment:
      port: 9103

  image-processing_1:
    lang: hybrid-py
    handler: ./image-processing
    image: jialianghuang/image-processing:latest
    limits:
      memory: 300M
      cpu: 1
    port: 5104
    environment:
      port: 9104

  pyaes_1:
    lang: hybrid-py
    handler: ./pyaes
    image: jialianghuang/pyaes:latest
    limits:
      memory: 200M
      cpu: 1
    port: 5105
    environment:
      port: 9105

  image-recognition_1:
    lang: hybrid-py
    handler: ./image-recognition
    image: jialianghuang/image-recognition:latest
    limits:
      memory: 888M
      cpu: 2
    port: 5106
    environment:
      port: 9106
      exec_timeout: 50
      write_timeout: 55

  video-processing_1:
    lang: hybrid-py
    handler: ./video-processing
    image: jialianghuang/video-processing:latest
    limits:
      memory: 300M
      cpu: 1
    port: 5107
    environment:
      port: 9107

  crypto_1:
    lang: hybrid-node18
    handler: ./crypto
    image: jialianghuang/crypto:latest
    limits:
      memory: 192M
      cpu: 1
    port: 5108
    environment:
      port: 9108

  image-flip-rotate_1:
    lang: hybrid-node18
    handler: ./image-flip-rotate
    image: jialianghuang/image-flip-rotate:latest
    limits:
      memory: 650M
      cpu: 1
    port: 5109
    environment:
      port: 9109

  js-json-serde_1:
    lang: hybrid-node18
    handler: ./js-json-serde
    image: jialianghuang/js-json-serde:latest
    limits:
      memory: 96M
      cpu: 1
    port: 5110
    environment:
      port: 9110

  json-serde_1:
    lang: hybrid-py
    handler: ./json-serde
    image: jialianghuang/json-serde:latest
    limits:
      memory: 116M
      cpu: 1
    port: 5111
    environment:
      port: 9111

  pagerank_1:
    lang: hybrid-py
    handler: ./pagerank
    image: jialianghuang/pagerank:latest
    limits:
      memory: 250M
      cpu: 1
    port: 5112
    environment:
      port: 9112

  chameleon_2:
    lang: hybrid-py
    handler: ./chameleon
    image: jialianghuang/chameleon:latest
    limits:
      memory: 400M
      cpu: 1
    port: 5202
    environment:
      port: 9202

  dynamic-html_2:
    lang: hybrid-py
    handler: ./dynamic-html
    image: jialianghuang/dynamic-html:latest
    limits:
      memory: 148M
      cpu: 1
    port: 5203
    environment:
      port: 9203

  image-processing_2:
    lang: hybrid-py
    handler: ./image-processing
    image: jialianghuang/image-processing:latest
    limits:
      memory: 300M
      cpu: 1
    port: 5204
    environment:
      port: 9204

  pyaes_2:
    lang: hybrid-py
    handler: ./pyaes
    image: jialianghuang/pyaes:latest
    limits:
      memory: 128M
      cpu: 1
    port: 5205
    environment:
      port: 9205

  image-recognition_2:
    lang: hybrid-py
    handler: ./image-recognition
    image: jialianghuang/image-recognition:latest
    limits:
      memory: 800M
      cpu: 2
    port: 5206
    environment:
      port: 9206
      exec_timeout: 50
      write_timeout: 55

  video-processing_2:
    lang: hybrid-py
    handler: ./video-processing
    image: jialianghuang/video-processing:latest
    limits:
      memory: 300M
      cpu: 1
    port: 5207
    environment:
      port: 9207

  crypto_2:
    lang: hybrid-node18
    handler: ./crypto
    image: jialianghuang/crypto:latest
    limits:
      memory: 170M
      cpu: 1
    port: 5208
    environment:
      port: 9208

  image-flip-rotate_2:
    lang: hybrid-node18
    handler: ./image-flip-rotate
    image: jialianghuang/image-flip-rotate:latest
    limits:
      memory: 624M
      cpu: 1
    port: 5209
    environment:
      port: 9209

  js-json-serde_2:
    lang: hybrid-node18
    handler: ./js-json-serde
    image: jialianghuang/js-json-serde:latest
    limits:
      memory: 128M
      cpu: 1
    port: 5210
    environment:
      port: 9210

  json-serde_2:
    lang: hybrid-py
    handler: ./json-serde
    image: jialianghuang/json-serde:latest
    limits:
      memory: 132M
      cpu: 1
    port: 5211
    environment:
      port: 9211

  pagerank_2:
    lang: hybrid-py
    handler: ./pagerank
    image: jialianghuang/pagerank:latest
    limits:
      memory: 300M
      cpu: 1
    port: 5212
    environment:
      port: 9212
